version: '2'
services:
    meteor:
      image: ulexus/meteor
      ports:
       - "8080:80"
      environment:
       - BUNDLE_URL=https://unee-t-media.s3-accelerate.amazonaws.com/frontend/15ec7da.tar.gz
       - ROOT_URL=${ROOT_URL}
       - BUGZILLA_URL=${BUGZILLA_URL}
       - BUGZILLA_ADMIN_KEY=${BUGZILLA_ADMIN_KEY}
       - MONGO_URL=mongodb://mongo:27017/mydatabase
      logging:
            driver: awslogs
            options:
              awslogs-region: ap-southeast-1
              awslogs-group: meteor
      links:
          - "mongo"

    mongo:
      image: mongo
      volumes:
        - '/data/db:/data/db'
      ports:
      - "27017:27017"
      logging:
              driver: awslogs
              options:
                awslogs-region: ap-southeast-1
                awslogs-group: mongo

